# Site settings
title: Teis Lindemark
email: teis.lindemark@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Teis Lindemark and I am a software developer, beer home brewer and an Agent backer.
  Disclaimer: The opinions expressed on this blog are my own personal and do not
  represent my employer's view in any way. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.teilin.net" # the base hostname & protocol for your site
twitter_username: TeisLindemark
github_username:  teilin

# Build settings
markdown: kramdown
